106 jobs status
TechAndCheck/zenodotus pull request #110
Opened 2021-12-10 20:55 UTC by oneroyalace

2022-01-03 15:50 UTC, oneroyalace commented
@cguess I've resolved merge conflicts on this branch, but we should probably merge #105 to master before this branch, as this branch is based off of that PR. 

Unfortunately there's not much in the way of testing on this branch because the changes are frontend-based (the status page) and queue based (move to sidekiq). 

To manually check that these changes are working though, you can run the following in the rails console:

```ruby
require 'sidekiq/api'
tweet_urls = [
  "https://twitter.com/JasonKander/status/1478016167679864836",
  "https://twitter.com/smwat/status/1478022399555739652",
  "https://twitter.com/greg_doucette/status/1477696042535735296",
  "https://twitter.com/BillAdairDuke/status/1478022935587614723",
  "https://twitter.com/seungminkim/status/1478022908538720261",
  "https://twitter.com/normative/status/1478021120251023361",
  "https://twitter.com/jeffjarvis/status/1478019870478548993",
  "https://twitter.com/thehill/status/1477678824280182790",
  "https://twitter.com/tressiemcphd/status/1476978397679075336",
  "https://twitter.com/RepLizCheney/status/1477723817200041988",
  "https://twitter.com/tressiemcphd/status/1478009292926201856",
  "https://twitter.com/ShaneGoldmacher/status/1477997873010819078",
  "https://twitter.com/farhip/status/1478000944042414082",
  "https://twitter.com/JonathanCohn/status/1477987859005116420",
  "https://twitter.com/PunchbowlNews/status/1478006865296601091",
  "https://twitter.com/NadiehBremer/status/1478003463430811650",
  "https://twitter.com/Martina/status/1477741805802246149",
  "https://twitter.com/TheEconomist/status/1478000715436072960",
  "https://twitter.com/brianstelter/status/1478000387185692673",
  "https://twitter.com/tcwittes/status/1477998719207456770",
  "https://twitter.com/frostyhk/status/1477872373072535552",
  "https://twitter.com/shmcminn/status/1477994333802541061",
  "https://twitter.com/ddale8/status/1477993680271253507",
  "https://twitter.com/NPRKelly/status/1477993406722985984",
  ]

tweet_urls.each do |url|
	Sources::Tweet.create_from_url! url
	puts "queue size: #{Sidekiq::Queue.new.size}"
end
```

You should see logs of the queue size, showing that the scraper tasks are being handled by SideKiq. Additionally, if you watch http://localhost:3000/jobs, you should see ActionCable updating the jobs tracker table there.

2022-01-03 21:43 UTC, cguess requested changes

2022-01-03 21:43 UTC, cguess commented on app/models/sources/instagram_post.rb
> +    # UnifiedTableRefreshJob.perform_later
Do we want to get rid of this?

2022-01-03 21:43 UTC, cguess commented on app/models/sources/tweet.rb
> +    # UnifiedTableRefreshJob.perform_later
Is this unnecessary?

2022-01-03 21:43 UTC, cguess commented on app/views/jobs_status/index.html.erb
> +      <%# unless @jobs_queue.empty? %>
Remove this probably?

2022-01-03 21:43 UTC, cguess commented on app/views/settings/index.html.erb
> +  <br>
These three `<br>` should probably be a CSS spacing instead

2022-01-03 21:43 UTC, cguess commented on config/initializers/figaro.rb
> +# Figaro.require_keys("FORKI_SERVER_URL")
Lets remove this if unneeded or uncomment it?

2022-01-03 21:43 UTC, cguess commented on db/migrate/20211114190617_create_facebook_videos.rb
> +#             :user,
Let's remove these comments

2022-01-03 21:43 UTC, cguess commented on test/channels/jobs_channel_test.rb
> +  # test "subscribes" do
Should this be running?

2022-01-03 21:43 UTC, cguess commented on test/controllers/jobs_tracker_controller_test.rb
> +  # test "the truth" do
clear this out or put tests in it

2022-01-04 14:44 UTC, oneroyalace commented on app/models/sources/instagram_post.rb
> +    # UnifiedTableRefreshJob.perform_later
I think so. I'll make an issue for fixing text search

2022-01-04 14:45 UTC, oneroyalace commented on app/views/jobs_status/index.html.erb
> +      <%# unless @jobs_queue.empty? %>
Yep

2022-01-04 14:45 UTC, oneroyalace commented on app/models/sources/tweet.rb
> +    # UnifiedTableRefreshJob.perform_later
Yes, removed

2022-01-04 15:03 UTC, oneroyalace commented on app/views/settings/index.html.erb
> +  <br>
This is changed in an incoming PR

2022-01-04 15:56 UTC, cguess approved these changes

2022-01-04 16:00 UTC, merged