Add ability to manage scrapes
TechAndCheck/zenodotus pull request #157
Opened 2022-03-28 21:40 UTC by cguess

This adds the ability to view, resubmit and delete scrapes that have not
been completed yet.

To test:
1. `rails db:migrate`
1. `rails test`

2022-03-28 21:46 UTC, reefdog commented on config/tailwind.config.js
> +        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
Just to sanity-check `Inter var` is the valid name of the font?

2022-03-28 21:52 UTC, reefdog requested changes
Very small UX request around confirmation language.

Also, when I run this I get a bunch of failing tests, but I suspect this is due to an incomplete setup. I'll resolve that with you separately (and update the README for #156 further as needed), and then check this again once my setup actually works.

2022-03-28 21:52 UTC, reefdog commented on app/views/jobs_status/index.html.erb
> +                    turbo_confirm: "Are you sure?"
UX request: can you customize this confirmation so it's more clear to the user which action they're confirming? Suggested: "Are you sure you want to delete this job?"

2022-03-28 21:52 UTC, reefdog commented on app/views/jobs_status/index.html.erb
> +                    turbo_confirm: "Are you sure?"
UX request: can you customize this confirmation so it's more clear to the user which action they're confirming? Suggested: "Are you sure you want to resubmit this job?"

2022-03-30 19:37 UTC, reefdog commented on config/tailwind.config.js
> +        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
Answering my own question here: [yup, `Inter var` is correct](https://tailwindui.com/documentation#optional-add-the-inter-font-family).

2022-03-30 19:37 UTC, reefdog commented on config/tailwind.config.js
> +        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
Answering my own question here: [yup, `Inter var` is correct](https://tailwindui.com/documentation#optional-add-the-inter-font-family).

2022-03-31 14:16 UTC, cguess commented
Yes. I’ll get to it in the next hour

-Christopher Guess
***@***.***
US/WhatsApp/Signal: +1 262.893.1037
PGP: AAE7 5171 0D81 B45B – https://keybase.io/cguess
On Mar 31, 2022, 10:03 -0400, Justin Reese ***@***.***>, wrote:
> @cguess Once #163 is merged into master, do you plan to rebase this branch from it? (Should I wait for that before continuing this review?)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-03-31 16:30 UTC, cguess commented
All cleaned up. @reefdog please take a look

2022-03-31 20:58 UTC, reefdog commented
@cguess Tests are currently running, but I just fired up the app and was greeted with a `NameError in Archive#index`, I think because of the same `jobs_status_path` issues you were fixing in 2db1b8da1ed4944a719b41cdb5682f71699e9be7. Might need a few more snipes:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/4731/161148104-8ced0d89-9a4d-48f5-8e1c-81dc47cb7b4f.png">

2022-03-31 21:25 UTC, reefdog requested changes
@cguess It's a clean test run! 🎉 The only issue is the error on `jobs_status_path` that I noted above, that causes rendering the header to throw an error. After that I think this is good to go.

…although it strikes me that I don't actually know how to test the _functionality_ of this in the browser.

2022-04-01 16:17 UTC, reefdog approved these changes

2022-04-01 16:18 UTC, merged