Equalize force nonforce rebase
TechAndCheck/zenodotus pull request #181
Opened 2022-04-15 19:35 UTC by cguess

2nd try on equalizing force between Hypatia and zenodotus.

To test:
- Make sure you have the sister branch to this running on Hypatia
- `rails t`

2022-04-18 17:03 UTC, oneroyalace commented on test/models/instagram_user_test.rb
> +    )["scrape_result"].first["post"]["user"] if @@zorki_user.nil?
Ah, does this prevent `InstagramMediaSource.extract` from being run before each individual test?

2022-04-18 17:04 UTC, cguess commented on test/models/instagram_user_test.rb
> +    )["scrape_result"].first["post"]["user"] if @@zorki_user.nil?
Yes, since it's the same exact request, this means it only has to run once per total run.

2022-04-18 17:04 UTC, cguess commented on test/models/instagram_user_test.rb
> +    )["scrape_result"].first["post"]["user"] if @@zorki_user.nil?
I've added this pattern to a few tests.

2022-04-18 19:40 UTC, reefdog requested changes
@cguess This runs great and the tests seem to pass. 🎉

```
Finished in 852.076312s, 0.1056 runs/s, 0.2817 assertions/s.
90 runs, 240 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Minitest to /Users/justin/Projects/duke/zenodotus/coverage. 878 / 1011 LOC (86.84%) covered.
```

I do have two small requests, but won't need a re-review after them.

2022-04-18 19:40 UTC, reefdog commented on app/models/scrape.rb
> +                     # debugger
Could you nix all these `#debugger` lines? May as well do it now than just have to remove them later.

2022-04-18 19:40 UTC, reefdog commented on .gitignore
> +.gitconfig
Sorry that we're beating this one to death, but: I don't think we need to blanket ignore `.gitconfig` as a rule! I just think that particular command belongs in the user's own config space (for me, `~/.gitconfig`) rather than in the repo's config space. (Side note: I've actually never seen a repo `.gitconfig` so didn't know it was a thing.)

My earlier review was suggesting that you move the `[alias]` block out of the repo's `.gitconfig` into your own userspace git config, not "leave it here but ignore it".

Any objection to that? My hesitance about this approach is I don't know if `.gitconfig` in the repo has a valid use case we may want in the future, and will have forgotten why we ignored it in the first place.

2022-04-18 22:07 UTC, oneroyalace approved these changes
LGTM

2022-04-19 15:19 UTC, cguess commented on .gitignore
> +.gitconfig
Point taken and agreed. I'll fix it.

2022-04-19 15:19 UTC, cguess commented on app/models/scrape.rb
> +                     # debugger
oh damn it!

2022-04-19 15:27 UTC, merged