31 video search
TechAndCheck/zenodotus pull request #201
Opened 2022-04-29 21:22 UTC by cguess

Add video search

    This adds full reverse video search with the same interface as we
    already had for images. From the user's standpoint it's the same, but
    the backend is all sorts of new things.

    To test:
    rails db:migrate
    rails t

    start the server, click "media search" and then upload a video to see if
    anything shows up. You may consider archiving a youtube video, and then
    searching using the same video file to make sure it returns stuff.

2022-05-03 17:28 UTC, oneroyalace requested changes

2022-05-03 17:28 UTC, oneroyalace commented on Gemfile
> +gem "zelkova", path: "~/Repositories/zelkova"
Local path!

2022-05-03 17:28 UTC, oneroyalace commented on app/models/image_search.rb
> +      videos.sort_by! { |video| video[:score] }
Should we note here that low score = low distance = better match? I usually assume that high score = better match. 

https://github.com/cguess/zelkova/blob/631cfbff1f150606cc75dba53b9040f62da70250/lib/zelkova/graph.rb#L87-L88

2022-05-03 17:44 UTC, oneroyalace requested changes

2022-05-03 17:44 UTC, oneroyalace commented on config/initializers/zelkova.rb
> +  graph = Zelkova.graph
Hm, I error out on lines 6 and 7. Should they just be:
```
graph = Zelkova::Graph.new
```

I don't see a radius attribute in `Zelkova::Graph`
https://github.com/cguess/zelkova/blob/631cfbff1f150606cc75dba53b9040f62da70250/lib/zelkova/graph.rb

2022-05-03 19:16 UTC, reefdog commented on app/models/image_search.rb
> +      videos.sort_by! { |video| video[:score] }
Oof, if that's the case, and if it's possible, I think we should rename `score` to `distance` or something. That would beat having to document usage, since it's possible that will repeatedly confuse people.

2022-05-03 19:21 UTC, reefdog commented on app/models/image_search.rb
> +        { video: hash.archive_item, score: video_hash[:distance] }
If renaming `score` to `distance` in the returned object is too high-impact, I wonder if we could do something else here, like invert the distance to generate an actual score. (Like, if distance is `0-1`, we could do like `score = 1-distance` or something? Basically I agree with @oneroyalace's concern about the expected polarity of `score`.)

2022-05-03 19:22 UTC, cguess commented on app/models/image_search.rb
> +        { video: hash.archive_item, score: video_hash[:distance] }
let's change it

2022-05-03 21:13 UTC, oneroyalace approved these changes
LGTM

2022-05-03 22:06 UTC, reefdog commented on app/models/image_search.rb
> +                ImageSearch.create!({ video: media_item, user: current_user })
If we haven't already, let's open a (low-priority) issue to rename the `ImageSearch` model to `MediaSearch`, for reasons that should be obvious lol.

2022-05-03 22:18 UTC, reefdog requested changes
I have just one code request (noted inline), but I should also note that testing in-browser (by locally downloading the Tyler the Creator video from Twitter, then uploading that back as the search) returned two search results, both for the correct archive item.

I was also unable to archive a new YouTube video to use for testing, but I'll assume that's unrelated to this and will figure it out separately.

2022-05-03 22:18 UTC, reefdog commented on app/models/image_search.rb
> +      # For videos we have to loop
Why is this comment up here? Feels like it should be down with the actual video logic?

2022-05-03 22:18 UTC, reefdog commented on app/models/image_search.rb
> +    else
I do wonder, since we have `self.videos`, if rather than this video-searching being just the `else` to the image-searching, it would make more sense if it were more verbose:

```ruby
if self.image.nil? == false
  # Image stuff
end

if self.video.nil? == false
  # Video stuff
end
```

There's no *functional* improvement there, but it feels a little weird that we're mode-switching into video search just based on the absence of an image search. (I think making it an `elsif` would also work, though I kinda like this explicitness.)

2022-05-04 19:44 UTC, reefdog commented
@cguess if you can merge the latest upstream in here, I can finish testing it out!

2022-05-05 17:31 UTC, reefdog commented
I'm running into the following two reproducible issues:

**1. Duplicate search results**
1. `rails db:reset` (for a clean database)
2. `youtube-dl https://t.co/It4oIhHk2C` to download the Lumberjack clip from Twitter
3. Perform a media search with the resulting download

What should happen: you get a search result!
What does happen: you get two search results:
<img width="800" alt="duplicate-results" src="https://user-images.githubusercontent.com/4731/166979597-72fbf9bf-3264-44a0-b021-0410856aaf88.png">

**2. YouTube search fails on missing template**
1. Add a YouTube video to the archive ([example](https://www.youtube.com/watch?v=Df7UtQTFUMQ))
2. `youtube-dl -f 22 https://www.youtube.com/watch?v=Df7UtQTFUMQ` to download it (in MP4 format, since the default is MKV which we don't support)
3. Perform a media search with the resulting download

What should happen: you get a search result!
What does happen: you get a Rails error about the missing YouTube post template:
<img width="800" alt="missing-post-template" src="https://user-images.githubusercontent.com/4731/166979849-404aa871-3959-4cbc-bf4a-076ba586acbd.png">

2022-05-05 17:55 UTC, oneroyalace commented
Linking this here: https://github.com/TechAndCheck/zenodotus/issues/213

2022-05-05 19:42 UTC, reefdog commented on app/models/concerns/dhashable.rb
> +      self.dhashes = Eikon.dhash_for_video(tempfile_path)
So this may be self-evident to someone who understands what's going in here, but why this is just a method call, while the image one a few lines up is forced into an array, is the sort of thing it'd be nice to clarify in a comment.

2022-05-05 19:45 UTC, reefdog approved these changes
This looks and acts mergeable! I do have a few inline comments about code clarity concerns, but I'll let you prioritize those. 👍

2022-05-05 19:48 UTC, cguess commented on app/models/concerns/dhashable.rb
> +      self.dhashes = Eikon.dhash_for_video(tempfile_path)
it's because image returns just a single image and video returns an array. A comment would be good, you're right I'll add now

2022-05-05 19:52 UTC, cguess commented on app/models/concerns/dhashable.rb
> +      self.dhashes = Eikon.dhash_for_video(tempfile_path)
done

2022-05-05 19:55 UTC, reefdog commented on app/views/image_search/_search_result_list_item_tweet.html.erb
> +<% result = result[:video] if result.has_key?(:video) %>
🚨 This line will trigger an error if the prior line succeeded, because `result` has been changed and no longer responds to the `has_key?` method.

We probably shouldn't reassign `result`.

2022-05-05 19:56 UTC, reefdog commented on app/views/image_search/_search_result_list_item_tweet.html.erb
> +<% result = result[:video] if result.has_key?(:video) %>
Let's go with something like this:

```erb
<% search_result = result[:image] if result.has_key?(:image) %>
<% search_result = result[:video] if result.has_key?(:video) %>
```

(Plus change the references elsewhere in the template of course.)

2022-05-17 14:41 UTC, merged