206 mock hypatia s3
TechAndCheck/zenodotus pull request #330
Opened 2022-08-30 20:22 UTC by oneroyalace

This PR creates mocks of Hypatia and our `AwsS3Downloader` client and uses those mocks to stub out the methods we use to access Hypatia/S3 in tests. With the intro of this PR, we can run Zenodotus tests without Hypatia/s3 access. 

Instead of scraping media posts to get data for tests, we load that data with mocks. This is, as you might image, much faster. Testing time should drop from 15+ minutes to ~3-4 minutes, most of which is spent transcoding media. 

## 76 files changed?? 
Sorry, there are tons of files changed in this PR. Nearly every test in our suite has been touched up. But here are some descriptions of and entry points to different parts of this PR: 

### S3 mocking
1. This PR creates an [S3 mock](https://github.com/TechAndCheck/zenodotus/blob/206-mock-hypatia-s3/test/aws_s3_mock.rb) class that stands in for `AwsS3Downloader` in tests. 
    1. The mock uses s3 keys to look for matching media filenames. If it finds a matching filename in our `test/mock_media` directory, it returns it. 
3. In `test_helper.rb`, we create a proc that's injected into each individual test file to stub out `AwsS3Downloader` with our `AwsS3Mock`. See [these](https://github.com/TechAndCheck/zenodotus/blob/5b3b5e4e45e5cc9553f5a594ab049e364a1ef972/test/test_helper.rb#L19-L21) lines
4. Within each test (see, e.g., [`InstagramPostTest`](https://github.com/TechAndCheck/zenodotus/blob/206-mock-hypatia-s3/test/models/instagram_post_test.rb)), we create an [s3-mocking block](https://github.com/TechAndCheck/zenodotus/blob/5b3b5e4e45e5cc9553f5a594ab049e364a1ef972/test/models/instagram_post_test.rb#L12-L16) that uses the proc mentioned in (2) to do the actual stubbing. 

### Hypatia mocking
1. This PR creates a [Hypatia mock module](https://github.com/TechAndCheck/zenodotus/blob/206-mock-hypatia-s3/test/hypatia_mock.rb/) stands in for Hypatia in tests. 
    1. The mock creates a hash that matches media post URLs to hypatia responses. When it receives a scrape request for a media post URL, it returns the corresponding hypatia response. 
3. When Minitest imports the mock module into [`test_helper.rb`](https://github.com/TechAndCheck/zenodotus/blob/206-mock-hypatia-s3/test/test_helper.rb), it runs the module's [`construct_typhoeus_hypatia_stub`](construct_typhoeus_hypatia_stub) method, which reroutes Typhoeus requests headed to Hypatia to our mock. 
4. All calls to Hypatia within tests are automatically mocked, so long as we have data for the URL the test tries to scrape from. If a URL isn't caught by the mock, we raise an exception

# Testing instructions
1. `bundle`
2. `rails db:migrate` (pulls in a migration from the base `post-screenshots` branch)
3. `rake test`

Here's my testing output:
```
Finished in 189.883972s, 0.5635 runs/s, 1.5325 assertions/s.
107 runs, 291 assertions, 0 failures, 1 errors, 0 skips
Coverage report generated for Minitest to /home/grog/hub/zenodotus/coverage. 1097 / 1352 LOC (81.14%) covered.
```
One test, `test_scrape_callback_works` fails for me on this branch and in `master`. @cguess is looking into it.

2022-08-30 21:57 UTC, reefdog requested changes
Asa, this is incredible work. Look at this! Look at this!

```
Finished in 35.828105s, 2.9865 runs/s, 8.1221 assertions/s.
107 runs, 291 assertions, 0 failures, 1 errors, 0 skips
Coverage report generated for Minitest to /Users/justin/Projects/duke/zenodotus/coverage. 1099 / 1354 LOC (81.17%) covered.
```

The one error is the callback one you already noted. 👏

I have a bunch of inline comments and suggestions, some of which should be non-controversial (typos and such), some of which might need conversation, and all of which you are welcome to object to entirely.

I do wonder if we should organize all the mock files into a `test/mocks` directory though. I know that would require modifying all the paths, but having the mock files at the root of `test/` feels weird, and if we put them in `test/mocks/` we could also just have `test/mocks/data/` and `test/mocks/media/` too. I leave this up to you though, it's basically just an OCD thing.

👏

2022-08-30 21:57 UTC, reefdog commented on app/models/sources/facebook_user.rb
> -      tempfile.close!
Two quick notes:

1. I have a vague memory of discovering that the path was no longer available after closing the file, even when assigned to a new variable. Which sounds apocryphal so tagging in @cguess, do you recall something similar? If that's the case, we should probably leave this here but I guess make it like `tempfile.close! if tempfile` or something.
2. If we _do_ determine moving the close is safe, we should move the associated comment (L88-89) too.

2022-08-30 21:57 UTC, reefdog commented on app/models/sources/instagram_user.rb
> -    tempfile.close!
I'm not a good enough engineer to know if we need to close the file or not, but I do think we should use the same pattern between this file and `facebook_user.rb`.

2022-08-30 21:57 UTC, reefdog commented on app/models/sources/youtube_channel.rb
> +      profile_image_path = tempfile.path
See other comments re: not closing this file. Again, I'm ambivalent about whether we do or not (I don't know the consequences), but I do think we should be consistent between the files.

2022-08-30 21:57 UTC, reefdog commented on test/controllers/archive_controller_test.rb
> +    # file.close
We can remove this line.

2022-08-30 21:57 UTC, reefdog commented on test/controllers/archive_controller_test.rb
>      # make a forced scrape call to Hypatia, then create it from there
Is this comment still an accurate description of what's going on? I can't quite tell based on reading through the code. If so, cool. If not, let's update.

2022-08-30 21:57 UTC, reefdog commented on test/hypatia_mock.rb
> +  # @params mock_data_directory: the name of the directory mocked data files are stored in
I don't think we need colons separating the var names from the description in the @param definition.

Also I hate to point this out but I think it should be `@param` not `@params`? 😬 Looks like that affects most method defs in this file.

2022-08-30 21:57 UTC, reefdog commented on test/hypatia_mock.rb
> +      file_path = "#{mock_data_directory}/#{fn}"
I'd recommend always using `File.join` to construct the path, to save us from any pain related to accidental opening/trailing slash issues, or weird hierarchy issues, or whatever. (I think these are actually generated from the `Dir` command earlier, rather than human-typed, so way less chance of error, but still would be a good safeguard against future weirdness IMO.)

2022-08-30 21:57 UTC, reefdog commented on test/hypatia_mock.rb
> +    mock_body = JSON.dump(mock_body)
I think this would double-encode the `["scrape_result"]` content. Just sanity-checking that that's okay!

2022-08-30 21:57 UTC, reefdog commented on test/hypatia_mock.rb
> +  # Returns a simple success response, imitating Hypatia's responsess to non-force scrape requests
`responsess` → `responses`

2022-08-30 21:57 UTC, reefdog commented on test/hypatia_mock.rb
> +  # end
Do we need to keep this around or can we remove it? (Fine if you have near-term plans for it.)

2022-08-30 21:57 UTC, reefdog commented on test/media_sources/youtube_media_source_test.rb
> +  test "extracting create a YoutubePost object" do
`create` → `creates`

2022-08-31 14:00 UTC, oneroyalace commented
> I do wonder if we should organize all the mock files into a `test/mocks` directory though. I know that would require modifying all the paths, but having the mock files at the root of `test/` feels weird, and if we put them in `test/mocks/` we could also just have `test/mocks/data/` and `test/mocks/media/` too. I leave this up to you though, it's basically just an OCD thing.

This bothered me a bit, too :). Happy to change it. Luckily, I'll only need to adjust the file paths in `test_helper.rb`. The rest of the tests inherit mock access from that helper file

2022-08-31 14:05 UTC, oneroyalace commented on app/media_sources/facebook_media_source.rb
> +    params = { auth_key: Figaro.env.HYPATIA_AUTH_KEY, url: @url, callback_id: scrape.id, force: "true" }
You know, I got confused because I saw that Hypatia checks whether the force parameter is set to `"true"` (string) as opposed to `true` (boolean). But I guess all HTTP query params are stringified, right? I'll change the force param to boolean types across Zenodotus

2022-08-31 14:38 UTC, oneroyalace commented on app/models/sources/facebook_user.rb
> -      tempfile.close!
@reefdog, I believe we're safe here because we assign `tempfile.path` to another variable before we call `tempfile.close`. Ruby is a pass-by-value language (at least for immutable data types), so once we've run `variable=tempfile.path`, we don't have to worry about what happens to `tempfile`. 

I'll move the L88-L89 comment as you suggested and keep this thread open in case @cguess has more to say

2022-08-31 14:41 UTC, oneroyalace commented on app/models/sources/facebook_user.rb
> -      tempfile.close!
```
[69, 78] in /home/grog/hub/zenodotus/app/models/sources/facebook_user.rb
   69:         # which obviously breaks everything)
   70:         tempfile = Tempfile.new(binmode: true)
   71:         tempfile.write("hey there!")
   72:         profile_image_path = tempfile.path
   73:         byebug
=> 74:         tempfile.close!
   75:         puts "Profile image path: #{profile_image_path}"
   76:         puts "Tempfile.path: #{profile_image_path}"
   77:       end
   78:
(byebug) tempfile.path.object_id
112120
(byebug) profile_image_path.object_id
112140
(byebug) n

[70, 79] in /home/grog/hub/zenodotus/app/models/sources/facebook_user.rb
   70:         tempfile = Tempfile.new(binmode: true)
   71:         tempfile.write("hey there!")
   72:         profile_image_path = tempfile.path
   73:         byebug
   74:         tempfile.close!
=> 75:         puts "Profile image path: #{profile_image_path}"
   76:         puts "Tempfile.path: #{profile_image_path}"
   77:       end
   78:
   79:       hash_to_return = {
(byebug) tempfile.path
nil
(byebug) profile_image_path
"/tmp/20220831-25162-9lcq57"

```
some proofy pudding ^

2022-08-31 14:42 UTC, oneroyalace commented on app/models/sources/facebook_user.rb
> -      tempfile.close!
Er, @cguess, thoughts on removing the comment altogether?

2022-08-31 14:43 UTC, reefdog commented on app/models/sources/facebook_user.rb
> -      tempfile.close!
Super, thanks for that. I can't remember _what_ exactly Chris and I were running into then. Carry on!

2022-08-31 14:56 UTC, reefdog commented on app/media_sources/facebook_media_source.rb
> +    params = { auth_key: Figaro.env.HYPATIA_AUTH_KEY, url: @url, callback_id: scrape.id, force: "true" }
Ah, I see. So the existing check was `== "true"`, but that was implicitly relying on HTTP params always being read as strings (which is valid), so you were making it coherent on the param-construction side.

I'm honestly not sure what's best to do here! Obviously we have to keep the check a string check… but should we always compose these values as strings when constructing the query? Taken to its extreme, that would lead us to do things like `query[:quantity] = quantity.to_s` for numbers or something. So I think your last comment is right… as much as possible let's do the "right thing" on each end (true boolean going in, string check coming out).

2022-08-31 14:57 UTC, reefdog commented on app/media_sources/facebook_media_source.rb
> +    params = { auth_key: Figaro.env.HYPATIA_AUTH_KEY, url: @url, callback_id: scrape.id, force: "true" }
BTW this is more a fun bit of 🤔, nothing critical. I fully trust whatever you think is right.

2022-08-31 15:07 UTC, oneroyalace commented on test/controllers/archive_controller_test.rb
>      # make a forced scrape call to Hypatia, then create it from there
I call upon @cguess. Should I revert my changes to this test (which still fails for me) and skip it or now?  I wanted to find a way for us to remove the `lib/assets/sample_instagram_scrape.json` file, which I _think_ we can now that we have similar files in the `test/mocks/data` directory

2022-08-31 15:08 UTC, oneroyalace commented on test/hypatia_mock.rb
> +  # @params mock_data_directory: the name of the directory mocked data files are stored in
Eeeeep you're probably right about both of those issues. I'll fix them up

2022-08-31 15:44 UTC, oneroyalace commented on test/hypatia_mock.rb
> +  # end
Nope! Thanks for the catch

2022-08-31 15:48 UTC, oneroyalace commented on test/hypatia_mock.rb
> +      file_path = "#{mock_data_directory}/#{fn}"
Done!

2022-08-31 18:34 UTC, cguess commented on app/models/sources/facebook_user.rb
> -      tempfile.close!
Yep, remove it. Closing a file is specifically a Windows thing and necessity anyways (though good practice) since Windows systems have some weird legacy stuff that means two programs can't even *read* a file at the same time. Linux/BSD/POSIX doesn't have this limitation.

2022-08-31 19:15 UTC, cguess reviewed
This is amazing, like awesome, beyond everything. Great work.

Weirdly, I'm getting this error while running tests:
```
/Users/christopher/Repositories/Reporters_Lab/zenodotus/test/controllers/archive_controller_test.rb:7:in `<class:ArchiveControllerTest>': uninitialized constant Minitest::Hooks (NameError)

  include Minitest::Hooks
                  ^^^^^^^
	from /Users/christopher/Repositories/Reporters_Lab/zenodotus/test/controllers/archive_controller_test.rb:5:in `<top (required)>'
	from /Users/christopher/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/christopher/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
```

Other notes to consider:
- Since the `after_all` is the same for every media source, should we consider monkey patching the `ActiveSupport::TestCase` to automatically include that?
- Ditto for `  include Minitest::Hooks`

2022-08-31 19:58 UTC, oneroyalace commented on test/controllers/jobs_tracker_controller_test.rb
> +    InstagramMediaSource.extract("https://www.instagram.com/p/CBcqOkyDDH8/", false)
They did. Do you think we could use those URLs in Hypatia's `ScraperControllerTest`

2022-08-31 20:03 UTC, oneroyalace commented
> * Since the `after_all` is the same for every media source, should we consider monkey patching the `ActiveSupport::TestCase` to automatically include that?
> * Ditto for `  include Minitest::Hooks`
@cguess I thought about that (or creating a new test class our tests could inherit from), but I think we have a few different types of test classes. Some inherit from `ActionDispatch::IntegrationTest`, some inherit from `ActiveSupport::TestCase`, etc

2022-08-31 20:13 UTC, reefdog commented on test/controllers/jobs_tracker_controller_test.rb
> +    InstagramMediaSource.extract("https://www.instagram.com/p/CBcqOkyDDH8/", false)
I'd advocate for clean URLs everywhere except in tests where you're explicitly testing URL parsing.

2022-08-31 20:15 UTC, cguess commented on test/controllers/jobs_tracker_controller_test.rb
> +    InstagramMediaSource.extract("https://www.instagram.com/p/CBcqOkyDDH8/", false)
Sounds good to me

2022-08-31 20:15 UTC, cguess commented
@oneroyalace that's totally fine and makes sense, disregard my idea.

2022-09-06 18:06 UTC, reefdog commented
It woooooorks! 🎉

2022-09-06 18:09 UTC, reefdog approved these changes
Huzzah!

2022-09-07 18:16 UTC, cguess approved these changes
MERGE THIS (great goddamn job)

2022-09-07 19:29 UTC, merged