Update `MediaReview` model
TechAndCheck/zenodotus pull request #373
Opened 2022-09-27 22:42 UTC by oneroyalace

This PR adds several attributes from https://schema.org/MediaReview to the `MediaReview` model. Most significantly, it introduces the idea of an `associatedClaimReview` to Zenodotus. To represent that attributes, it creates a new `ClaimReview` model, which `belongs_to MediaReview`. 

This PR alters our `claim-review-schema.json` JSON schema file (renamed to `media-review-schema.json`). Before we merge the PR, I'd like to get ahold of a bunch of live `MediaReview` JSON objects and run them through Zenodotus to makes sure the updated schema doesn't cause issues. 

# Before merging
1. @cguess I'll ping you in our devshop channel to ask about how to grab those `MediaReview` JSONs
2. Depending on what I see in (1), I may remove [these](https://github.com/TechAndCheck/zenodotus/blob/58294f22ca64a6c33093e049025a21a7424b58e9/app/models/archive_item.rb#L24-L28) lines from `archive_item.rb`. The schema.org schema suggests we don't need them and can access a top-level `originalMediaUrl` attribute. 

# Testing instructions
1. `rails db:migrate`
2. `rails db:reset` (to reset seeds)
3.  `rake`

2022-09-28 17:01 UTC, reefdog commented
Initial code-scan looks good. @oneroyalace could you rebase this from `master` to re-apply your changes to the ingest controller (and the archive/ingest controller tests), and then I'll actually run automated tests?

2022-09-28 19:13 UTC, oneroyalace commented
@reefdog Rebased!

2022-09-28 19:27 UTC, reefdog commented on app/models/archive_item.rb
> +    # That callback will triger the Scrape fulfillment processwhich
`triger` → `trigger`

2022-09-28 19:27 UTC, reefdog commented on app/models/archive_item.rb
> +    # which will atttach this MediaReview to the ArchiveItem
`atttach` → `attach`

2022-09-28 19:35 UTC, oneroyalace commented on app/models/archive_item.rb
> +    # That callback will triger the Scrape fulfillment processwhich
Ty! I really need to add a spell checker to my text editor

2022-09-28 19:36 UTC, oneroyalace commented on app/models/archive_item.rb
> +    # which will atttach this MediaReview to the ArchiveItem
More letters better, right?

2022-09-28 20:20 UTC, reefdog commented on app/models/archive_item.rb
> +    # which will atttach this MediaReview to the ArchiveItem
Absollutelyy!

2022-09-28 20:23 UTC, reefdog commented on db/migrate/20220926191035_update_media_review.rb
> +      t.jsonb :item_reviewed, null: false
Okay so per our conversation in Slack and after some more thinking, I think capturing these null constraints here only and _not_ on the model will bite us.

Can you at least update the model to validate the presence of any required attributes? Whether we remove the null constraints as well is a larger architectural/design question; I'm leaning to "yes, only keep null constraints where necessary for data integrity (primary keys, required foreign keys, etc.)" but open to yours and @cguess's thoughts.

2022-09-28 20:26 UTC, reefdog requested changes
Two thoughts here:

1. These migrations will currently only run on a clean database. If we want to be able to run them on an existing database, we'll need to remove the `null` constraints on the new columns. I genuinely don't know if that matters, just raising it.
2. See my inline comment re: the null constraints at all. Happy to be over-ruled if you and @cguess disagree, but I'm thinking that capturing a required model attribute only in the db schema and not on the model is a pattern we'll end up regretting. I'm separately a little skeptical we need to have null constraints on required fields in the database at all, but open to thoughts! (If we go with "we don't", then I know there are lots of null constraints that could be lifted.)

2022-09-29 20:18 UTC, oneroyalace commented on db/migrate/20220926191035_update_media_review.rb
> +      t.jsonb :item_reviewed, null: false
Addressed!

2022-09-29 20:21 UTC, oneroyalace commented
Agreed @reefdog. I've removed non primary key + foreign key null constraints from both models

2022-09-29 20:39 UTC, reefdog approved these changes
This all looks great to me and the tests run!

I called out a comment typo, asked one question, and made one future suggestion, but none are crucial and this otherwise LGTM.

2022-09-29 20:39 UTC, reefdog commented on app/models/claim_review.rb
> +  belongs_to :media_review, optional: true, class_name: "MediaReview"
Do we want to add any model validations to `ClaimReview`? Not suggesting we should, just wondering.

2022-09-29 20:39 UTC, reefdog commented on app/models/archive_item.rb
> +    # That callback will trigger the Scrape fulfillment processwhich
`processwich` → `process which`

I am the 👑 of substantive suggestions.

2022-09-29 20:39 UTC, reefdog commented on db/migrate/20220926191035_update_media_review.rb
> +class UpdateMediaReview < ActiveRecord::Migration[7.0]
Not worth resolving here, but I'd aim for a more descriptive migration name in the future just for sanity. 😆

2022-09-30 21:29 UTC, oneroyalace commented on app/models/archive_item.rb
> +    # That callback will trigger the Scrape fulfillment processwhich
Someday I'm actually going to install a spellchecker

2022-09-30 21:36 UTC, merged

2022-09-30 21:40 UTC, reefdog commented on app/models/archive_item.rb
> +    # That callback will trigger the Scrape fulfillment processwhich
But then what will become of my code reviews??