Update to run fully through via FactStream
TechAndCheck/zenodotus pull request #395
Opened 2022-10-11 16:54 UTC by cguess

This fully removes twitter (again) and then adds a few fixes to make sure Zenodotus can properly receive stuff from FactStream.

To test:
- `bundle install`
- Unfortunately it's really hard to test the ingestion from FactStream without a lot of set up so the best route I just `rails test` as usual.

2022-10-11 18:03 UTC, reefdog requested changes
@cguess There seems to be one accidentally change here that breaks tests (see inline comment). Also the [diff](https://github.com/TechAndCheck/zenodotus/pull/395/files) is a little weird… I wonder if some commits are missing / haven't been pushed yet? All I'm seeing is a change to the Sidekiq gem versioning pattern, removing some seed data, and removing the line that lets us scrape tweets in Archive.org URLs. The description implies there should be more going on?

2022-10-11 18:11 UTC, cguess commented on app/media_sources/twitter_media_source.rb
> -    url = MediaSource.extract_post_url_if_needed(url)
Ah yes, that was accidental, adding back (merging sucks!)

2022-10-11 18:36 UTC, reefdog approved these changes
All seems fine! Tests run, though as you noted I can't really test any further functionality than that. Still, 👍.

2022-10-11 19:31 UTC, oneroyalace commented on db/seeds.rb
> -)
Why are we removing all of the seeds?

2022-10-11 20:19 UTC, reefdog requested changes
Actually yanking my approval on this one, I suspect the final state of it got borked during the merge or rebase from `master`. @cguess I think we should pair on the review of it when you have a moment!

2022-10-14 21:24 UTC, cguess commented
> Actually yanking my approval on this one, I suspect the final state of it got borked during the merge or rebase from `master`. @cguess I think we should pair on the review of it when you have a moment!

Sounds good. Monday, first thing then

2022-10-17 16:33 UTC, reefdog approved these changes
It all runs clean now and I see new commits!

2022-10-17 16:39 UTC, merged