ClaimReview and MediaReview blueprints
TechAndCheck/zenodotus pull request #407
Opened 2022-10-24 20:36 UTC by oneroyalace

This PR adds BluePrints for the `ClaimReview` and `MediaReview`models. 

When using these BluePrints to create JSON objects, we're guaranteed to get objects that have all the keys we expect, even if the corresponding `ClaimReview` or `MediaReview` `ActiveRecord` is missing them. 

# Testing
- `bundle` (install `blueprinter`)
- `rake`

2022-10-24 21:44 UTC, oneroyalace commented
@reefdog Just to make sure, is it okay if I copy the `itemReviewed->mediaItemAppearance` value straight to the JSON output? Do I need to do any validation there? The value is of type `array`, and it looks like it can be inhabited by a few different types of content. 

Here's what I'm talking about: 
```json
// from MediaReview
"itemReviewed": {
		"@type": "MediaReviewItem",
		"creator": {
			"@type": "Person",
			"name": "Instagram user",
			"url": "https://www.instagram.com/wrong_saloon_bear/?hl=en"
		},
		"interpretedAsClaim": {
			"@type": "Claim",
			"description": "Mariah Carey faked getting her COVID-19 vaccine because the needle can't be seen coming out of her arm."
		},
		"mediaItemAppearance": [
			{
				"@type": "VideoObjectSnapshot",
				"description": "An Instagram user posted a zoomed-in version of a video of Mariah Carey receiving a COVID vaccination, writing 'It's all a scam, don't celebrate celebrities.'"
			},
			{
				"@type": "VideoObjectSnapshot",
				"contentUrl": "https://www.instagram.com/p/CNtao_WA0Dr/",
				"archivedAt": "https://archive.is/EXAMPLE"
			}
		]
	}
```

2022-10-24 21:54 UTC, reefdog commented
@oneroyalace I thiiiiink so? To be honest, I'm probably the least informed person about what should be in this data structure. That's probably a better question for @cguess and/or @ericaryan and/or @joelwluther!

2022-10-24 21:55 UTC, reefdog commented on db/seeds.rb
> +    # "originalMediaLink": "https://www.foobar.com/3",
Can we nix the commented-out code? Unless we really need to keep it around.

2022-10-24 21:57 UTC, reefdog commented on test/models/claim_review_test.rb
> +  test "test_claim_review_blueprinter_output_has_required_characteristics" do
Oh btw these test names can be written as a sentence / with spaces, and also it will self-prefix with the word "test"; ActiveSupport handles the underscoring and prefixing. (I don't really care / you're welcome to leave it as is, just a heads up.)

2022-10-24 22:02 UTC, reefdog requested changes
I only have one requested change: that (if possible) our tests compare the `to_json` Blueprinter call with an actual chunk of JSON based on the provided input. That way we can test not just the expected structure/keys, but that the fields are being populated with the expected values. If that's not a good idea for some reason, let me know!

That one thought aside, this is great and approved. I should note that I'm not a Blueprinter expert so I have no eye for any sort of recommended optimizations or anything, but it LGTM!

2022-10-25 17:55 UTC, oneroyalace commented on db/seeds.rb
> +    # "originalMediaLink": "https://www.foobar.com/3",
Yep! Thanks for catching this

2022-10-25 17:59 UTC, oneroyalace commented on test/models/claim_review_test.rb
> +    assert claim_review_json["itemReviewed"]["author"].has_key?("sameAs")
You're right. This is the cleaner way to go :). Adding it in now

2022-10-25 20:07 UTC, reefdog approved these changes
Looks great! Thanks for making the test changes. 🙏

2022-10-25 20:10 UTC, merged