Also broadcast if the post wasn't found
TechAndCheck/zenodotus pull request #413
Opened 2022-10-25 23:33 UTC by cguess

Welp, this fixes an issue where if the post wasn't found then the scrape was never broadcasted.

Whoops

2022-10-31 15:31 UTC, reefdog approved these changes
I trust this solves something, lol.

2022-11-01 21:47 UTC, reefdog requested changes
Actually, revoking my approval, because I actually ran tests and am consistently getting this error (not on `master`):

```
Error:
MediaVault::IngestControllerTest#test_Submitting_real_JSON_but_with_a_bad_schemas_to_the_ingest_API_gives_a_400:
NoMethodError: undefined method `[]' for nil:NilClass

    appearance = media_review["itemReviewed"]["mediaItemAppearance"].select do |appearance|
                                             ^^^^^^^^^^^^^^^^^^^^^^^
    app/models/archive_item.rb:24:in `create_from_media_review'
    app/controllers/media_vault/ingest_controller.rb:164:in `archive_from_media_review'
    app/controllers/media_vault/ingest_controller.rb:79:in `submit_media_review'
    test/controllers/media_vault/ingest_controller_test.rb:21:in `block in <class:IngestControllerTest>'

rails test test/controllers/media_vault/ingest_controller_test.rb:20
```

Can you take a look @cguess and see if it's legit, or a broken test, or what?

2022-11-07 18:57 UTC, reefdog commented on app/controllers/media_vault/ingest_controller.rb
> +      else T.absurd(self)
`T.absurd` 😆, I can't believe it's [real](https://sorbet.org/docs/exhaustiveness)!

2022-11-07 19:01 UTC, reefdog commented on app/controllers/media_vault/ingest_controller.rb
> +    render(json: response_payload, status: 400)
Total side note (as you are correctly being consistent w/the rest of this file), but I've been preferring the [keywords](https://guides.rubyonrails.org/layouts_and_rendering.html#options-for-render) myself, just to save us a lookup to the cheat sheet.

No change requested of course, just raising the point.

2022-11-07 19:02 UTC, reefdog commented on app/controllers/media_vault/ingest_controller.rb
>      media_review_json = JSON.parse(typed_params.media_review_json)
Should this try to catch `JSONParseError` or no? Just making sure I understand the point of it.

2022-11-07 19:09 UTC, reefdog requested changes
Thanks for fixing that test! I'm getting a new failing test, and it also looks like you accidentally checked in a change to the production database configuration.

Here's the test that's failing for me now:
```
Error:
MediaVault::IngestControllerTest#test_Can_archive_media_review_from_json:
ActiveRecord::RecordInvalid: Validation failed: Media authenticity category can't be blank
    app/models/archive_item.rb:40:in `create_from_media_review'
    app/controllers/media_vault/ingest_controller.rb:202:in `archive_from_media_review'
    app/controllers/media_vault/ingest_controller.rb:103:in `submit_media_review'
    test/controllers/media_vault/ingest_controller_test.rb:88:in `block in <class:IngestControllerTest>'

rails test test/controllers/media_vault/ingest_controller_test.rb:87
```

I've verified it's not breaking on `master`.

It also looks like you committed a regression to the schema version? Though it's not showing up in the "Files changed" tab, commit 9b4fa08d5399c322f916e80fdc849b77704ea418 shows the regression and is also reflected in the local code when I pull, which means running `rails db:migrate` locally creates a change (updating the schema version).

2022-11-07 19:09 UTC, reefdog commented on config/database.yml
> +  # url: <%= ENV["DATABASE_URL"] %>
I don't think this change was intended to be committed, was it?

2022-11-07 19:09 UTC, reefdog commented on app/controllers/media_vault/ingest_controller.rb
>      media_review_json = JSON.parse(typed_params.media_review_json)
🤦 Apologies, I forgot to expand GitHub's interface to see the whole context.

2022-11-07 19:10 UTC, cguess commented on config/database.yml
> +  # url: <%= ENV["DATABASE_URL"] %>
damn it, fixing now

2022-11-07 19:18 UTC, reefdog approved these changes
Tests run clean, diff looks good! 👍

2022-11-07 19:18 UTC, merged