Supplement mediareview model
TechAndCheck/zenodotus pull request #95
Opened 2021-09-28 06:16 UTC by oneroyalace

This PR adds several models corresponding to child attributes of the publicly posted `MediaReview` object schema. Several of the names are awkward right now, so I'm very open to change.

2021-09-28 17:24 UTC, cguess requested changes

2021-09-28 17:24 UTC, cguess commented on app/helpers/application_helper.rb
> +  def self.convert_from_camel_case(str)
Rails already supports this out of the box https://api.rubyonrails.org/classes/String.html#method-i-underscore

2021-09-28 17:24 UTC, cguess commented on app/models/archive_item.rb
> +      original_media_link: url,  # remove? Not in schema
Keep this, we want the data even if it's not in the official schema.

2021-09-28 17:24 UTC, cguess commented on app/models/archive_item.rb
> +      media_authenticity_category: media_review["mediaAuthenticityCategory"], # enum?
Enum's not a bad idea, but it's also not finalized, so let's just keep it as a string.

2021-09-28 17:24 UTC, cguess commented on app/models/archive_item.rb
> +      media_authenticity_category: media_review["mediaAuthenticityCategory"], # enum?
Question: are the keys (i.e. `mediaAuthenticityCategory`) coming in from the scraped JS directly?

2021-09-28 17:24 UTC, cguess commented on db/migrate/20210927200203_create_media_item_appearance.rb
> +      t.text :_type
don't use _type, since underscores usually imply some sort of private property in most languages, or at least something set aside. But since we're the ones running this we will always want that exposed. just `type` is probably fine.

2021-09-28 17:24 UTC, cguess commented on db/migrate/20210927200524_create_media_review_item_author.rb
> +      t.text :_type
Same for `_type` as above

2021-09-28 17:24 UTC, cguess commented on test/controllers/text_search_controller_test.rb
> +class TextSearchControllerTest < ActionDispatch::IntegrationTest
Should there be any tests here?

2021-09-28 17:26 UTC, oneroyalace commented on app/helpers/application_helper.rb
> +  def self.convert_from_camel_case(str)
Sweet! Changing

2021-09-28 17:51 UTC, oneroyalace commented on db/migrate/20210927200203_create_media_item_appearance.rb
> +      t.text :_type
Unfortunately rails/postgres yelled at me for using the column name `type`. What do you think of `type_`?

2021-09-28 17:53 UTC, oneroyalace commented on test/controllers/text_search_controller_test.rb
> +class TextSearchControllerTest < ActionDispatch::IntegrationTest
Yes, there should. I'll submit a new PR with text search tests

2021-09-28 18:13 UTC, oneroyalace commented on app/models/archive_item.rb
> +      media_authenticity_category: media_review["mediaAuthenticityCategory"], # enum?
@cguess For the most part, yes. I added a few `media_review` prefixes to some of the models, though.

Here's some mapping documentation: 

# Original Schema
```
{
   "@context":"https://schema.org",
   "@type":"MediaReview",
   "datePublished":"2021-04-27",
   "url":"https://www.politifact.com/factchecks/2021/apr/27/instagram-posts/mariah-carey-didnt-fake-getting-her-covid-19-vacci/",
   "author":{
      "@type":"Organization",
      "name":"PolitiFact",
      "url": "https://politifact.com"
   },
   "mediaAuthenticityCategory":"DecontexualizedContent",
    "originalMediaContextDescription":"Singer Mariah Carey shared a video of herself receiving a COVID-19 vaccination.",
   "itemReviewed":{
      "@type":"MediaReviewItem",
      "creator":{
         "@type":"Person",
         "name":"Instagram user",
         "url":"https://www.instagram.com/wrong_saloon_bear/?hl=en"
      },
      "interpretedAsClaim":{
         "@type":"Claim",
         "description": "Mariah Carey faked getting her COVID-19 vaccine because the needle can’t be seen coming out of her arm."
      },
      "mediaItemAppearance":[
         {
            "@type":"VideoObjectSnapshot",
            "description": "An Instagram user posted a zoomed-in version of a video of Mariah Carey receiving a COVID vaccination, writing ‘It’s all a scam, don’t celebrate celebrities.’"
         },
         {
            "@type":"VideoObjectSnapshot",
            "contentUrl":"https://www.instagram.com/p/CNtao_WA0Dr/",
            "archivedAt":"https://archive.is/EXAMPLE"
         }
      ]
   }
}

# Zenodotus tables
```
## top-level `media_review` attributes
- `@context`: Removed. Always `schema.org`
- `@type`: Removed. Always `MediaReview`
- `datePublished` -> `date_published`
- `url` -> `url`
- `mediaAuthenticityCategory` -> `media_authenticity_category`
- `originalMediaContextDescription` -> `original_media_context_description`

### `media_review.author` -> `media_review.author`
- `@type` -> `_type` (can change per discussion above)
- `name` -> `name`
- `url` -> `url`

### `media_review.itemReviewed -> `media_review.media_review_item_reviewed`
(I can change ^ if we're okay having a postgres table named `item_reviewed`
- `@type` -> `_type` (above)
- new: `interpreted_as_claim` (see below)

### `media_review.itemReviewed.interpretedAsClaim`
I didn't create a table/model for this attribute object because it only has a single field. Instead, I flattened it and added it to `itemReviewed` as a text attribute. 

#### `media_review.itemReviewed.creator` -> `media_review.media_review_item_reviewed.media_review_item_author`
^ This is the aforementioned awful one. Maybe the table name could change from `media_review_item_item_author` to `media_creator`? Not sure how to balance loyalty to the schema vs. descriptive table names vs. brevity
-`@type` -> `_type` (can change per discussion above)
- `name` -> `name`
- `url` -> `url`

#### `media_review.itemReviewed.mediaItemAppearance` -> `media_review.media_review_item_reviewed.media_item_appearance`
- `@type` -> `_type` (above)
- `description` -> `description`
- `contentUrl` -> `content_url`
- `archivedAt` -> `archived_at`

2021-09-28 18:46 UTC, cguess commented on db/migrate/20210927200203_create_media_item_appearance.rb
> +      t.text :_type
OK, in taht case it's fine.

2021-09-28 18:47 UTC, cguess commented on db/migrate/20210927200524_create_media_review_item_author.rb
> +      t.text :_type
same, keep as is.

2021-10-11 14:35 UTC, cguess reviewed
Just two questions.

2021-10-11 14:35 UTC, cguess commented on app/models/media_review_models/media_review_author.rb
> +  belongs_to :media_review, optional: true, class_name: "MediaReviewModels::MediaReview"
Why is this optional?

2021-10-11 14:35 UTC, cguess commented on app/models/media_review_models/media_review_item.rb
> +  belongs_to :media_review, optional: true, class_name: "MediaReviewModels::MediaReview"
Same: why is this optional?

2021-12-23 13:38 UTC, closed without merging